### PR TITLE
Add p3.md

### LINKED ISSUE #10: 第三題
第13組

### PR DESCRIPTION
**Pull request by scps940707**
Closes #10 

@daphnechen00 @juhuitseng [p3.md](https://github.com/scps940707/Homework-1/blob/e18ea0606fab35b33fbf1fc19c5e175914c08327/p3.md)

### CODE REVIEW

**Comment by juhuitseng** [comment]
有再做更改~

**Comment by scps940707** [comment]
@juhuitseng [p3.md](https://github.com/scps940707/Homework-1/blob/0342e303b82c7ecbf9dd1c9ef4e8262228dd6664/p3.md)

**Review by c910335 — CHANGES_REQUESTED** [review]
https://github.com/NCU-CSIE-Algorithmics-A-1061/Homework-1/issues/10#issuecomment-336772320

**Comment by c910335** [comment]
@juhuitseng [p3.md](https://github.com/scps940707/Homework-1/blob/05e08b1812957095328f806071dbbb393970b0d6/p3.md)

**Comment by c910335** [comment]
@juhuitseng [p3.md](https://github.com/scps940707/Homework-1/blob/a72d0b8951a082b9a285cfd4e088f13db93563cb/p3.md)

**Comment by juhuitseng** [comment]
嗯嗯 謝謝助教
我要自己merge嗎？

**Pull request merged**
